Repository OurMenu/OurMenu-BE, pull requests merged in 2024-08, with the labels that each got.

#24 fix: environment variable
  docker-compose.yml
Labels: :bug: 버그

#38 Feat/onboarding
  src/main/java/com/ourMenu/backend/domain/onboarding/api/OnBoardingController.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/response/GetOnboardingResponse.java
  src/main/java/com/ourMenu/backend/domain/onboarding/application/OnBoardService.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/Answer.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/Question.java
  src/main/java/com/ourMenu/backend/domain/onboarding/util/S3Util.java
  src/main/java/com/ourMenu/backend/global/config/WebConfig.java
Labels: :wave:기능 추가

#42 Feat/search track
  src/main/java/com/ourMenu/backend/domain/store/api/StoreController.java
  src/main/java/com/ourMenu/backend/domain/store/api/response/GetSearchHistory.java
  src/main/java/com/ourMenu/backend/domain/store/api/response/GetStoresSearch.java
  src/main/java/com/ourMenu/backend/domain/store/application/StoreService.java
  src/main/java/com/ourMenu/backend/domain/store/application/UserStoreService.java
  src/main/java/com/ourMenu/backend/domain/store/dao/UserStoreRepository.java
  src/main/java/com/ourMenu/backend/domain/store/domain/UserStore.java
  src/main/java/com/ourMenu/backend/global/argument_resolver/UserId.java
Labels: :wave:기능 추가

#49 fix: userId annotation
  src/main/java/com/ourMenu/backend/domain/onboarding/api/OnBoardingController.java
  src/main/java/com/ourMenu/backend/domain/onboarding/application/OnBoardService.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/Answer.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/AnswerFood.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/AnswerType.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/Question.java
  src/main/java/com/ourMenu/backend/domain/store/api/StoreController.java
  src/main/java/com/ourMenu/backend/global/argument_resolver/UserId.java
Labels: :bug: 버그

#52 Fix/account
  src/main/java/com/ourMenu/backend/domain/user/api/request/ChangePasswordRequest.java
  src/main/java/com/ourMenu/backend/domain/user/api/request/LoginRequest.java
  src/main/java/com/ourMenu/backend/domain/user/api/request/SignUpRequest.java
  src/main/java/com/ourMenu/backend/domain/user/domain/User.java
  src/main/java/com/ourMenu/backend/global/util/JwtProvider.java
Labels: :bug: 버그

#66 Fix/init db
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  docker-compose.yml
  mysql/init/init.sql
  src/main/java/com/ourMenu/backend/init/InitUser.java
  src/main/resources/application.yml
Labels: :ocean: 개발 환경

#68 Feat/develop
  mysql/init/init.sql
  src/main/java/com/ourMenu/backend/domain/menu/api/MenuApiController.java
  src/main/java/com/ourMenu/backend/domain/menu/application/MenuService.java
  src/main/java/com/ourMenu/backend/domain/menu/application/PlaceService.java
  src/main/java/com/ourMenu/backend/domain/menu/dao/MenuRepository.java
  src/main/java/com/ourMenu/backend/domain/menu/domain/Menu.java
  src/main/java/com/ourMenu/backend/domain/menu/dto/request/PatchMenuRequest.java
  src/main/java/com/ourMenu/backend/domain/menu/dto/request/PostMenuRequest.java
  src/main/java/com/ourMenu/backend/domain/menu/dto/request/PostPhotoRequest.java
  src/main/java/com/ourMenu/backend/domain/menu/dto/response/MenuDto.java
  src/main/java/com/ourMenu/backend/domain/menu/dto/response/PostMenuResponse.java
  src/main/java/com/ourMenu/backend/domain/menulist/application/MenuListService.java
  src/main/java/com/ourMenu/backend/domain/menulist/dao/MenuListRepository.java
  src/test/java/com/ourMenu/backend/MenuController.java
  src/test/java/com/ourMenu/backend/onboarding/OnboardingTest.java
Labels: :wave:기능 추가

#71 Fix/search
  src/main/java/com/ourMenu/backend/domain/store/api/response/GetMenuSearch.java
  src/main/java/com/ourMenu/backend/domain/store/api/response/GetStoresSearch.java
Labels: :bug: 버그

#77 Feat/onboarding
  src/main/java/com/ourMenu/backend/domain/menu/application/MenuService.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/OnBoardingController.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/response/GetQuestionRecommands.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/response/GetRecommend.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/response/GetTagRecommends.java
  src/main/java/com/ourMenu/backend/domain/onboarding/application/OnBoardingService.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/DefaultTag.java
  src/main/java/com/ourMenu/backend/domain/onboarding/util/S3Util.java
Labels: :wave:기능 추가

#86 Feat/article
  mysql/init/init.sql
  src/main/java/com/ourMenu/backend/domain/article/api/ArticleController.java
  src/main/java/com/ourMenu/backend/domain/article/api/request/ArticleMenuRequest.java
  src/main/java/com/ourMenu/backend/domain/article/api/request/PostArticleRequest.java
  src/main/java/com/ourMenu/backend/domain/article/api/request/PutArticleRequest.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/ArticleMenuResponse.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/ArticleResponse.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/CommunityArticle.java
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleMenuService.java
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
  src/main/java/com/ourMenu/backend/domain/article/dao/ArticleMenuRepository.java
  src/main/java/com/ourMenu/backend/domain/article/dao/ArticleRepository.java
  src/main/java/com/ourMenu/backend/domain/article/domain/Article.java
  src/main/java/com/ourMenu/backend/domain/article/domain/ArticleMenu.java
  src/main/java/com/ourMenu/backend/domain/article/domain/ORDER_CRITERIA.java
  src/main/java/com/ourMenu/backend/domain/article/exception/NoSuchArticleException.java
  src/main/java/com/ourMenu/backend/domain/article/exception/NoSuchArticleMenuException.java
  src/main/java/com/ourMenu/backend/domain/menu/domain/MenuImage.java
  src/main/java/com/ourMenu/backend/global/exception/ErrorCode.java
  src/test/java/com/ourMenu/backend/article/ArticleServiceTest.java
  src/test/java/com/ourMenu/backend/menu/MenuControllerTest.java
Labels: :wave:기능 추가

#87 Fix/onboarding
  src/main/java/com/ourMenu/backend/domain/menu/application/MenuService.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/OnBoardingController.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/DefaultTag.java
Labels: :bug: 버그

#89 feat: add get user articles api
  src/main/java/com/ourMenu/backend/domain/user/api/UserController.java
  src/main/java/com/ourMenu/backend/domain/user/api/response/UserArticleResponse.java
  src/main/java/com/ourMenu/backend/domain/user/application/UserService.java
  src/main/java/com/ourMenu/backend/domain/user/dao/UserDao.java
Labels: :wave:기능 추가

#91 Fix/onboarding
  src/main/java/com/ourMenu/backend/domain/onboarding/api/response/GetOnboardingResponse.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/Answer.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/AnswerFood.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/AnswerImg.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/DefaultTag.java
  src/main/java/com/ourMenu/backend/domain/onboarding/domain/Question.java
  src/main/java/com/ourMenu/backend/domain/onboarding/util/S3Util.java
Labels: :scissors: 리펙토링

#95 Fix/article
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
  src/main/java/com/ourMenu/backend/domain/article/domain/Article.java
  src/main/java/com/ourMenu/backend/domain/article/domain/ArticleMenu.java
Labels: :bug: 버그

#104 Fix/onboarding
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
  src/main/java/com/ourMenu/backend/domain/menu/application/MenuService.java
  src/main/java/com/ourMenu/backend/domain/menu/dao/MenuRepository.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/OnBoardingController.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/response/GetRecommend.java
  src/main/java/com/ourMenu/backend/domain/onboarding/application/OnBoardingService.java
  src/test/java/com/ourMenu/backend/article/ArticleServiceTest.java
Labels: :bug: 버그

#107 Fix/onboarding
  mysql/init/init.sql
  src/main/java/com/ourMenu/backend/domain/article/api/ArticleController.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/ArticleMenuResponse.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/ArticleResponse.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/CommunityArticle.java
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
  src/main/java/com/ourMenu/backend/domain/article/dao/ArticleRepository.java
  src/main/java/com/ourMenu/backend/domain/article/domain/ArticleMenu.java
  src/main/java/com/ourMenu/backend/domain/onboarding/application/OnBoardingService.java
Labels: :bug: 버그, :wave:기능 추가, :snake: 엔티티 변경

#108 Fix/article
  mysql/init/init.sql
  src/main/java/com/ourMenu/backend/domain/article/api/ArticleController.java
  src/main/java/com/ourMenu/backend/domain/article/api/request/ArticleMenuRequest.java
  src/main/java/com/ourMenu/backend/domain/article/api/request/DownloadArticleMenu.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/ArticleMenuResponse.java
  src/main/java/com/ourMenu/backend/domain/article/api/response/DownloadArticleMenuResponse.java
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
  src/main/java/com/ourMenu/backend/domain/article/domain/ArticleMenu.java
Labels: :wave:기능 추가, :snake: 엔티티 변경

#109 feat: DELETE/article/{articleId}
  src/main/java/com/ourMenu/backend/domain/article/api/ArticleController.java
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
Labels: :wave:기능 추가

#119 Fix/onboarding
  src/main/java/com/ourMenu/backend/domain/menu/application/MenuService.java
  src/main/java/com/ourMenu/backend/domain/menu/dao/MenuRepository.java
  src/main/java/com/ourMenu/backend/domain/menu/dto/MenuIdentifier.java
  src/main/java/com/ourMenu/backend/domain/onboarding/api/OnBoardingController.java
  src/main/java/com/ourMenu/backend/domain/onboarding/application/OnBoardingService.java
Labels: :bug: 버그

#122 Fix/article
  src/main/java/com/ourMenu/backend/domain/article/application/ArticleService.java
Labels: :bug: 버그
